### ISSUE TITLE
 ASP.NET MVC Examples

### ISSUE THREAD

**Issue by martosource** [bernos/MediatR.Extensions#1]
Are there any examples of using MediatR.Extensions with ASP.NET MVC?

**Comment by afifmohammed** [comment]
@trustorm are there any particular extensions you are after? we were using the validation and autofac extensions (with asps.net web api). but then I removed them both as I modified the mediator itself to directly take a reference on autofac, and for the validators i prefer hand wiring them so its clearly discoverable as opposed to the extension magically wiring it into autofac.

**Comment by getuliojr** [comment]
I trying to understand how to use this extensions, but didn´t find any example. I am working with Owin + Webapi 2 + Autofac + MediatR. How will I extend it to use log4net for example ?
